# Generated by Django 4.2 on 2025-08-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(upload_to='faces/')),
                ('face_encoding', models.BinaryField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_time', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, upload_to='recognitions/')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reconocimiento.person')),
            ],
            options={
                'ordering': ['-recognition_time'],
            },
        ),
    ]
